# script auto-generated by phenix.molprobity


from __future__ import absolute_import, division, print_function
from six.moves import cPickle as pickle
from six.moves import range
try :
  import gobject
except ImportError :
  gobject = None
import sys

class coot_extension_gui(object):
  def __init__(self, title):
    import gtk
    self.window = gtk.Window(gtk.WINDOW_TOPLEVEL)
    scrolled_win = gtk.ScrolledWindow()
    self.outside_vbox = gtk.VBox(False, 2)
    self.inside_vbox = gtk.VBox(False, 0)
    self.window.set_title(title)
    self.inside_vbox.set_border_width(0)
    self.window.add(self.outside_vbox)
    self.outside_vbox.pack_start(scrolled_win, True, True, 0)
    scrolled_win.add_with_viewport(self.inside_vbox)
    scrolled_win.set_policy(gtk.POLICY_AUTOMATIC, gtk.POLICY_AUTOMATIC)

  def finish_window(self):
    import gtk
    self.outside_vbox.set_border_width(2)
    ok_button = gtk.Button("  Close  ")
    self.outside_vbox.pack_end(ok_button, False, False, 0)
    ok_button.connect("clicked", lambda b: self.destroy_window())
    self.window.connect("delete_event", lambda a, b: self.destroy_window())
    self.window.show_all()

  def destroy_window(self, *args):
    self.window.destroy()
    self.window = None

  def confirm_data(self, data):
    for data_key in self.data_keys :
      outlier_list = data.get(data_key)
      if outlier_list is not None and len(outlier_list) > 0 :
        return True
    return False

  def create_property_lists(self, data):
    import gtk
    for data_key in self.data_keys :
      outlier_list = data[data_key]
      if outlier_list is None or len(outlier_list) == 0 :
        continue
      else :
        frame = gtk.Frame(self.data_titles[data_key])
        vbox = gtk.VBox(False, 2)
        frame.set_border_width(6)
        frame.add(vbox)
        self.add_top_widgets(data_key, vbox)
        self.inside_vbox.pack_start(frame, False, False, 5)
        list_obj = residue_properties_list(
          columns=self.data_names[data_key],
          column_types=self.data_types[data_key],
          rows=outlier_list,
          box=vbox)

# Molprobity result viewer
class coot_molprobity_todo_list_gui(coot_extension_gui):
  data_keys = [ "rama", "rota", "cbeta", "probe" ]
  data_titles = { "rama"  : "Ramachandran outliers",
                  "rota"  : "Rotamer outliers",
                  "cbeta" : "C-beta outliers",
                  "probe" : "Severe clashes" }
  data_names = { "rama"  : ["Chain", "Residue", "Name", "Score"],
                 "rota"  : ["Chain", "Residue", "Name", "Score"],
                 "cbeta" : ["Chain", "Residue", "Name", "Conf.", "Deviation"],
                 "probe" : ["Atom 1", "Atom 2", "Overlap"] }
  if (gobject is not None):
    data_types = { "rama" : [gobject.TYPE_STRING, gobject.TYPE_STRING,
                             gobject.TYPE_STRING, gobject.TYPE_FLOAT,
                             gobject.TYPE_PYOBJECT],
                   "rota" : [gobject.TYPE_STRING, gobject.TYPE_STRING,
                             gobject.TYPE_STRING, gobject.TYPE_FLOAT,
                             gobject.TYPE_PYOBJECT],
                   "cbeta" : [gobject.TYPE_STRING, gobject.TYPE_STRING,
                              gobject.TYPE_STRING, gobject.TYPE_STRING,
                              gobject.TYPE_FLOAT, gobject.TYPE_PYOBJECT],
                   "probe" : [gobject.TYPE_STRING, gobject.TYPE_STRING,
                              gobject.TYPE_FLOAT, gobject.TYPE_PYOBJECT] }
  else :
    data_types = dict([ (s, []) for s in ["rama","rota","cbeta","probe"] ])

  def __init__(self, data_file=None, data=None):
    assert ([data, data_file].count(None) == 1)
    if (data is None):
      data = load_pkl(data_file)
    if not self.confirm_data(data):
      return
    coot_extension_gui.__init__(self, "MolProbity to-do list")
    self.dots_btn = None
    self.dots2_btn = None
    self._overlaps_only = True
    self.window.set_default_size(420, 600)
    self.create_property_lists(data)
    self.finish_window()

  def add_top_widgets(self, data_key, box):
    import gtk
    if data_key == "probe" :
      hbox = gtk.HBox(False, 2)
      self.dots_btn = gtk.CheckButton("Show Probe dots")
      hbox.pack_start(self.dots_btn, False, False, 5)
      self.dots_btn.connect("toggled", self.toggle_probe_dots)
      self.dots2_btn = gtk.CheckButton("Overlaps only")
      hbox.pack_start(self.dots2_btn, False, False, 5)
      self.dots2_btn.connect("toggled", self.toggle_all_probe_dots)
      self.dots2_btn.set_active(True)
      self.toggle_probe_dots()
      box.pack_start(hbox, False, False, 0)

  def toggle_probe_dots(self, *args):
    if self.dots_btn is not None :
      show_dots = self.dots_btn.get_active()
      overlaps_only = self.dots2_btn.get_active()
      if show_dots :
        self.dots2_btn.set_sensitive(True)
      else :
        self.dots2_btn.set_sensitive(False)
      show_probe_dots(show_dots, overlaps_only)

  def toggle_all_probe_dots(self, *args):
    if self.dots2_btn is not None :
      self._overlaps_only = self.dots2_btn.get_active()
      self.toggle_probe_dots()

class rsc_todo_list_gui(coot_extension_gui):
  data_keys = ["by_res", "by_atom"]
  data_titles = ["Real-space correlation by residue",
                 "Real-space correlation by atom"]
  data_names = {}
  data_types = {}

class residue_properties_list(object):
  def __init__(self, columns, column_types, rows, box,
      default_size=(380,200)):
    assert len(columns) == (len(column_types) - 1)
    if (len(rows) > 0) and (len(rows[0]) != len(column_types)):
      raise RuntimeError("Wrong number of rows:\n%s" % str(rows[0]))
    import gtk
    self.liststore = gtk.ListStore(*column_types)
    self.listmodel = gtk.TreeModelSort(self.liststore)
    self.listctrl = gtk.TreeView(self.listmodel)
    self.listctrl.column = [None]*len(columns)
    self.listctrl.cell = [None]*len(columns)
    for i, column_label in enumerate(columns):
      cell = gtk.CellRendererText()
      column = gtk.TreeViewColumn(column_label)
      self.listctrl.append_column(column)
      column.set_sort_column_id(i)
      column.pack_start(cell, True)
      column.set_attributes(cell, text=i)
    self.listctrl.get_selection().set_mode(gtk.SELECTION_SINGLE)
    for row in rows :
      self.listmodel.get_model().append(row)
    self.listctrl.connect("cursor-changed", self.OnChange)
    sw = gtk.ScrolledWindow()
    w, h = default_size
    if len(rows) > 10 :
      sw.set_size_request(w, h)
    else :
      sw.set_size_request(w, 30 + (20 * len(rows)))
    sw.set_policy(gtk.POLICY_AUTOMATIC, gtk.POLICY_AUTOMATIC)
    box.pack_start(sw, False, False, 5)
    inside_vbox = gtk.VBox(False, 0)
    sw.add(self.listctrl)

  def OnChange(self, treeview):
    import coot # import dependency
    selection = self.listctrl.get_selection()
    (model, tree_iter) = selection.get_selected()
    if tree_iter is not None :
      row = model[tree_iter]
      xyz = row[-1]
      if isinstance(xyz, tuple) and len(xyz) == 3 :
        set_rotation_centre(*xyz)
        set_zoom(30)
        graphics_draw()

def show_probe_dots(show_dots, overlaps_only):
  import coot # import dependency
  n_objects = number_of_generic_objects()
  sys.stdout.flush()
  if show_dots :
    for object_number in range(n_objects):
      obj_name = generic_object_name(object_number)
      if overlaps_only and not obj_name in ["small overlap", "bad overlap"] :
        sys.stdout.flush()
        set_display_generic_object(object_number, 0)
      else :
        set_display_generic_object(object_number, 1)
  else :
    sys.stdout.flush()
    for object_number in range(n_objects):
      set_display_generic_object(object_number, 0)

def load_pkl(file_name):
  pkl = open(file_name, "rb")
  data = pickle.load(pkl)
  pkl.close()
  return data

data = {}
data['rama'] = [('A', ' 154 ', 'TYR', 0.008030543155127164, (10.564999999999998, -18.715999999999998, -9.459))]
data['omega'] = []
data['rota'] = [('A', '  46 ', 'SER', 0.11779394951013128, (9.713999999999999, -10.515, 30.538000000000007)), ('A', '  46 ', 'SER', 0.1343285695338636, (9.715, -10.517, 30.558000000000003)), ('A', '  47 ', 'GLU', 0.013206173051395995, (12.21, -10.069, 33.408)), ('A', '  65 ', 'ASN', 0.2239555668281745, (11.646999999999998, -27.760000000000016, 27.690000000000005)), ('A', '  86 ', 'VAL', 0.299540011045867, (18.775999999999996, -17.593, 16.367)), ('A', '  88 ', 'LYS', 0.0, (18.256, -24.174, 15.937000000000001)), ('A', ' 135 ', 'THR', 0.05774774164104748, (14.944, -1.0860000000000005, 10.212)), ('A', ' 222 ', 'ARG', 0.012903826943328, (12.029, 20.56, -19.429000000000002)), ('A', ' 222 ', 'ARG', 0.0, (12.068000000000001, 20.47, -19.519)), ('A', ' 262 ', 'LEU', 0.006071460843061549, (19.790000000000006, 11.483000000000004, -16.228)), ('A', ' 303 ', 'VAL', 0.05514770898166249, (6.673, -12.743, -14.272))]
data['cbeta'] = []
data['probe'] = [(' A 155  ASP  HA ', ' A 306  GLN  HB2', -0.584, (9.087, -22.339, -8.399)), (' A  40  ARG  HD3', ' A  85  CYS  HA ', -0.568, (20.7, -15.649, 19.591)), (' A 279  ARG  HE ', ' A 280  THR  H  ', -0.508, (-2.405, 14.473, -8.72)), (' A 175  THR HG22', ' A 181  PHE  HA ', -0.499, (19.637, -9.552, 13.447)), (' A 222 AARG  HG3', ' A 222 AARG  O  ', -0.493, (13.45, 22.009, -20.876)), (' A 226  THR HG23', ' A 229  ASP  H  ', -0.483, (25.425, 16.897, -11.698)), (' A 279  ARG  HA ', ' A 279  ARG  NE ', -0.474, (-2.585, 16.321, -8.18)), (' A 118  TYR  CE2', ' A 144  SER  HB3', -0.474, (2.434, -10.836, 15.384)), (' A  34  ASP  N  ', ' A  34  ASP  OD1', -0.466, (15.468, -31.443, 9.183)), (' A 107  GLN  O  ', ' A 110  GLN  HG3', -0.465, (18.621, -4.488, 0.528)), (' A  95  ASN  HB3', ' A  98  THR  OG1', -0.463, (10.182, -29.497, 5.853)), (' A  92  ASP  N  ', ' A  92  ASP  OD1', -0.446, (11.694, -34.896, 15.164)), (' A  67  LEU HD12', ' A  74  GLN HE21', -0.446, (4.88, -30.047, 23.398)), (' A  63  ASN  OD1', ' A  80  HIS  ND1', -0.444, (18.278, -29.69, 23.133)), (' A  31  TRP  CE2', ' A  75  LEU HD21', -0.444, (8.172, -30.142, 12.313)), (' A 295  ASP  OD1', ' A 298  ARG  NH2', -0.422, (10.146, -7.271, -6.537)), (' A 222 BARG  H  ', ' A 222 BARG  HG3', -0.419, (10.868, 21.502, -17.528)), (' A 223  PHE  CD1', ' A 223  PHE  N  ', -0.415, (13.753, 20.976, -17.372)), (' A 276  MET  HE3', ' A 281  ILE HG13', -0.408, (3.169, 12.803, -8.034)), (' A 108  PRO  HB3', ' A 132  PRO  HA ', -0.403, (19.425, 0.918, 4.163))]
handle_read_draw_probe_dots_unformatted("molprobity_probe.txt", 0, 0)
show_probe_dots(True, True)
gui = coot_molprobity_todo_list_gui(data=data)
